const userTypes = {
  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SIGN_OUT_USER_START: "SIGN_OUT_USER_START",
  SIGN_OUT_USER_SUCCESS: "SIGN_OUT_USER_SUCCESS",
  SIGN_UP_USER_START: "SIGN_UP_USER_START",
  USER_ERROR: "USER_ERROR",
  USER_FORM_ADD_START: "USER_FORM_ADD_START",
  USER_FORM_ADD_SUCCESS: "USER_FORM_ADD_SUCCESS",
  USER_FORM_UPDATE_START: "USER_FORM_UPDATE_START",
  USER_FORM_UPDATE_SUCCESS: "USER_FORM_UPDATE_SUCCESS",
  USER_FORM_DELETE_START: "USER_FORM_DELETE_START",
  USER_FORM_DELETE_SUCCESS: "USER_FORM_DELETE_SUCCESS",
  USER_FORM_CALCULATE_START: "USER_FORM_CALCULATE_START",
  USER_FORM_CALCULATE_SUCCESS: "USER_FORM_CALCULATE_SUCCESS",
};

export default userTypes;
